cleaning up the EKS cluster and k8s before the destroying the terraform code

diff --git a/.github/workflows/infrastructure-destroy.yaml b/.github/workflows/infrastructure-destroy.yaml
--- a/.github/workflows/infrastructure-destroy.yaml
+++ b/.github/workflows/infrastructure-destroy.yaml
@@ -22,6 +22,13 @@ jobs:
     steps:
       - name: "Checkout Code"
         uses: actions/checkout@v4
+      
+      - name: Set up Kubeconfig
+        run: aws eks update-kubeconfig --name baashe-devops-cluster --region us-east-1
+
+      - name: Helm Cleanup
+        run: |
+          helm uninstall ecommerce --namespace default --wait || echo "Release not found, skipping..."
 
       - name: "Safety Check"
         run: |
